import Head from 'next/head'
import React from 'react'
import Button from '@/components/Button'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button text="CSR" />
      <Button text="SSG" />
      <Button text="SSR" />
   
      <Link href="/ssg">
        SSG
      </Link>
      <Link href="/ssr">
        SSR
      </Link>

      <main> 


      </main>
    </>
  )
}
